---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action 🧪'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Test local GitHub Action'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 25 # Increase this timeout value as needed
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 'Checkout sample O-RAN-SC repository'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          # Caution: this is a live project and may change at any time
          repository: 'o-ran-sc/oam-oam-controller'
          path: 'oam-oam-controller'

      # - name: "Running local action: ${{ github.repository }}"
      #   uses: ./
      #   with:
      #     jdk-version: '21'
      #     mvn-version: '3.9.5'
      #     make-targets: 'build'
      #     path_prefix: 'oam-oam-controller'
